# Generated by Django 4.1.5 on 2023-01-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todocategory_title_alter_todoitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.todocategory', to_field='title'),
        ),
    ]
