# Generated by Django 4.1.5 on 2023-01-26 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_reminders', models.BooleanField()),
                ('is_paid', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_recurring', models.BooleanField()),
                ('amount', models.FloatField()),
                ('name', models.TextField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('next_reminder', models.DateField()),
                ('frequency', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('biweek', 'Biweekly'), ('month', 'Monthly'), ('bimonth', 'Bimonthly')], default='month', max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bill_item',
                'verbose_name_plural': 'bill_items',
                'db_table': 'bills_item',
            },
        ),
    ]
