# Generated by Django 4.1.5 on 2023-01-27 02:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('recurring', models.CharField(choices=[('1', 'One time only'), ('2', 'Weekly'), ('3', 'Every 2 weeks'), ('4', 'Monthly'), ('5', 'Every 2 months'), ('6', 'Quarterly'), ('7', 'Every 6 months'), ('8', 'Yearly')], default='1', max_length=24)),
                ('reminder', models.CharField(choices=[('1', 'None'), ('2', '1 day'), ('3', '2 days'), ('4', '3 days'), ('5', '1 week'), ('6', '2 weeks')], default='1', max_length=24)),
                ('due_date_reminder', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('bill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.billtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bill_item',
                'verbose_name_plural': 'bill_items',
                'db_table': 'bills',
            },
        ),
    ]
