# Generated by Django 4.1.5 on 2023-01-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_amount_alter_bill_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
