# Generated by Django 4.1.5 on 2023-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_bill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_title', models.CharField(max_length=50)),
            ],
        ),
    ]
