# Generated by Django 4.1.5 on 2023-01-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_simplebill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='enable_reminders',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='next_reminder',
        ),
        migrations.AlterModelTable(
            name='bill',
            table=None,
        ),
    ]
