# Generated by Django 4.1.5 on 2023-01-26 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_alter_bill_options_rename_name_bill_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleBill',
        ),
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
